### ISSUE TITLE
Develop a function to empty the shopcart

### ISSUE THREAD

**Issue by Yvonne98XU** [CSCI-GA-2820-FA22-003/shopcarts#16]
**As a** User
**I need a way** to delete all the products in shopcart
**So that**  I can empty the whole shopcart at once

**Assumptions**

- After the shopcart got emptied, the shopcart should be remained in the service, only the products in it got deleted.

**Acceptance Criteria:**

```gherkin
Given the service is available
When I empty the shopcart
Then there should be no product in the shopcart when the transaction succeeds
Or it should return the corresponding error code if the operation fails
```

**Comment by zqf0722** [comment]
Since we already have an issue #4 to update the shopcarts which includes deletion, we won't have another API that does the same thing. However, we could be a function for emptying the whole shopcarts.

**Comment by zqf0722** [comment]
Closed because of duplicated issues.
