### ISSUE TITLE
Develop a REST API service to show items in the shopcart based on filters

### ISSUE THREAD

**Issue by HanNight** [CSCI-GA-2820-FA22-003/shopcarts#18]
**As a** User
**I need** a way to filter the items in my shopcart and show the result.
**So that** I can easily view my shopcart based on my certain filter.

**Assumptions**
- The base url is ```/shopcarts/<id>```
- The method of this API should be GET
- Url should return all items in the shopcart that satisfies the filter in a json string

**Acceptance Criteria:**

```gherkin
Given the service is available
When I call the URL `GET /shopcarts/<id>?filterID=<id_of_filter>`
Then it should return a list of items in the shopcart according to the filter
```

**Comment by zqf0722** [comment]
Let's put it in the icebox since we currently have no context of filters. We need an issue to create filters first

**Comment by zqf0722** [comment]
Closed because of duplicated issues.
