### ISSUE TITLE
Develop a REST API service to Add an item to the shopcart

### ISSUE THREAD

**Issue by zqf0722** [CSCI-GA-2820-FA22-003/shopcarts#4]
**As a** User
**I need** to add items to the shopcart
**So that** I can buy them later

**Assumptions**

- The url is `/shopcarts/<id>/items`, and the method is POST
- The parameters of this body are  `name`, `product_id`, `quantity`, and `price`, `time`
- user_id and product_id should be unique and can query the product in this shopcart
- The quantity should not be negative

**Acceptance Criteria:**
```gherkin
Given the service is available
When I call the URL `POST /shopcarts/<id>`
Then the change of this shopcart should be visible and correct.
```

**Comment by Yuhao-Fan** [comment]
according to the description, shopcart should have following properties: product id, product name, and quantity

**Comment by zqf0722** [comment]
> according to the description, shopcart should have following properties: product id, product name, and quantity

Edit the issue according to the comment. Thanks for the notification.
